import pygame
from pygame.locals import *
pygame.init()

global TLWDTH, TLHGHT, SCRNWDTH, SCRNHGHT, CMTLRNC, PLW, PLH, P_WALKSPEED, P_WALKACCEL, P_MAXFALLSPEED, PS3, FPS, GRAV, P_RUNACCEL, P_AIRFRICTION, P_AIRRUNACCEL, P_MAXAIRSPEED, P_MAXRISESPEED, C_WALL,C_MAI,C_PANEL,C_SPARK, C_DOOR, C_WARP, C_MOVEPLAT, CLASSES

C_WALL = "Wall"
C_MAI = "Mai"
C_SPARK = "Spark"
C_DOOR = "Door"
C_WARP = "Warp"
C_MOVEPLAT = "MovePlat"
CLASSES = [C_WALL,C_MAI,C_SPARK,C_DOOR,C_WARP,C_MOVEPLAT]
TLWDTH = 70
TLHGHT = 70
PLW = 42
PLH = 42
SCRNWDTH = 1200
SCRNHGHT = 720
CMTLRNC = 20 

P_WALKSPEED = 10 #10 
P_WALKACCEL = .7
P_MAXRUNSPEED = 10 #20
P_RUNACCEL = 3.5 #2
P_RUNDECEL = 1.5

P_FRICTION = .20 #percent of horizontal acceleration to remove.

P_SHORTHOP = -18 #-30
P_JUMPEXTENSION = -6 #-.8
P_MAXFALLSPEED = 25
P_MAXRISESPEED = -20 #-30
P_AIRRUNACCEL = 1.2
P_MAXAIRSPEED = 12 #30

P_AIRFRICTION = .02

GRAV = 1.5 #2.5
PS3 = {"L1":10,"L2":12,"R1":11,"R2":13,"X":14,"O":13,"Tri":12,"Sqr":15,"Sel":0,"Str":3,"L3":1,"R3":2,"DL":7,"DU":4,"DR":5,"DD":6,"home":16,"LSX":0,"LSY":1,"RSX":2,"RSY":3}
FPS = 45

